### ISSUE TITLE
/bin/sh: /usr/bin/rm: /usr/bin/coreutils: bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by cervajs** [eniocarboni/docker-rockylinux-systemd#2]
STEP 1/5: FROM rockylinux:9
Resolved "rockylinux" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
Trying to pull docker.io/library/rockylinux:9...
Getting image source signatures
Copying blob 9d28f3f24f51 skipped: already exists
Copying config 656f801c02 done
Writing manifest to image destination
Storing signatures
STEP 2/5: ENV container docker
--> 7eed84af90b
STEP 3/5: RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); rm -f /lib/systemd/system/multi-user.target.wants/*;rm -f /etc/systemd/system/*.wants/*;rm -f /lib/systemd/system/local-fs.target.wants/*; rm -f /lib/systemd/system/sockets.target.wants/*udev*; rm -f /lib/systemd/system/sockets.target.wants/*initctl*; rm -f /lib/systemd/system/basic.target.wants/*;rm -f /lib/systemd/system/anaconda.target.wants/*;
/bin/sh: line 1: cd: /lib/systemd/system/sysinit.target.wants/: No such file or directory
rm: cannot remove 'afs': Is a directory
rm: cannot remove 'dev': Is a directory
rm: cannot remove 'etc': Is a directory
rm: cannot remove 'home': Is a directory
/bin/sh: /usr/bin/rm: /usr/bin/coreutils: bad interpreter: No such file or directory
/bin/sh: /usr/bin/rm: /usr/bin/coreutils: bad interpreter: No such file or directory
/bin/sh: /usr/bin/rm: /usr/bin/coreutils: bad interpreter: No such file or directory
/bin/sh: /usr/bin/rm: /usr/bin/coreutils: bad interpreter: No such file or directory
/bin/sh: /usr/bin/rm: /usr/bin/coreutils: bad interpreter: No such file or directory
/bin/sh: /usr/bin/rm: /usr/bin/coreutils: bad interpreter: No such file or directory
/bin/sh: /usr/bin/rm: /usr/bin/coreutils: bad interpreter: No such file or directory
/bin/sh: /usr/bin/rm: /usr/bin/coreutils: bad interpreter: No such file or directory
/bin/sh: /usr/bin/rm: /usr/bin/coreutils: bad interpreter: No such file or directory
/bin/sh: /usr/bin/rm: /usr/bin/coreutils: bad interpreter: No such file or directory
/bin/sh: /usr/bin/rm: /usr/bin/coreutils: bad interpreter: No such file or directory
/bin/sh: /usr/bin/rm: /usr/bin/coreutils: bad interpreter: No such file or directory
/bin/sh: /usr/bin/rm: /usr/bin/coreutils: bad interpreter: No such file or directory
/bin/sh: /usr/bin/rm: /usr/bin/coreutils: bad interpreter: No such file or directory
/bin/sh: /usr/bin/rm: /usr/bin/coreutils: bad interpreter: No such file or directory
/bin/sh: /usr/bin/rm: /usr/bin/coreutils: bad interpreter: No such file or directory
/bin/sh: /usr/bin/rm: /usr/bin/coreutils: bad interpreter: No such file or directory
/bin/sh: /usr/bin/rm: /usr/bin/coreutils: bad interpreter: No such file or directory
/bin/sh: /usr/bin/rm: /usr/bin/coreutils: bad interpreter: No such file or directory
/bin/sh: /usr/bin/rm: /usr/bin/coreutils: bad interpreter: No such file or directory
Error: error building at STEP "RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); rm -f /lib/systemd/system/multi-user.target.wants/*;rm -f /etc/systemd/system/*.wants/*;rm -f /lib/systemd/system/local-fs.target.wants/*; rm -f /lib/systemd/system/sockets.target.wants/*udev*; rm -f /lib/systemd/system/sockets.target.wants/*initctl*; rm -f /lib/systemd/system/basic.target.wants/*;rm -f /lib/systemd/system/anaconda.target.wants/*;": error while running runtime: exit status 126

**Comment by eniocarboni** [comment]
Thanks @cervajs, fixed.
